name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

permissions:
  contents: read
  packages: write

concurrency:
  group: cd-${{ github.event.inputs.environment }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/dopeguard-backend
  FRONTEND_IMAGE: ghcr.io/${{ github.repository_owner }}/dopeguard-frontend

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE}}:latest
            ${{ env.BACKEND_IMAGE}}:${{steps.meta.outputs.image_tag}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ steps.meta.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: ${{ github.event.inputs.environment}}

    steps:
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            cd "${{ vars.DEPLOY_PATH }}"

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            docker pull ${{ env.BACKEND_IMAGE }}:${{ needs.build-and-push.outputs.image_tag }}
            docker pull ${{ env.FRONTEND_IMAGE }}:${{ needs.build-and-push.outputs.image_tag }}

            export BACKEND_IMAGE="${{ env.BACKEND_IMAGE }}:${{ needs.build-and-push.outputs.image_tag }}"
            export FRONTEND_IMAGE="${{ env.FRONTEND_IMAGE }}:${{ needs.build-and-push.outputs.image_tag }}"

            docker compose down
            docker compose up -d

            docker image prune -af

            curl -f "${{ vars.APP_HEALTHCHECK_URL }}"
